[config]
version_check = false
prefer = "darkness"

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/matugen.conf'

[templates.ghostty]
input_path = './templates/ghostty/colors.ghostty'
output_path = '~/.config/ghostty/colors.ghostty'

# [templates.obsidian]
# input_path = './templates/obsidian/obsidian.css'
# output_path = 'yourOwnPath/to/obsidianVault/.obsidian/snippets/matugen.css'

[templates.zed]
input_path = './templates/zed/zed-colors.json'
output_path = '~/.config/zed/themes/matugen.json'


[templates.m3colors]
input_path = '~/.config/matugen/templates/colors.json'
output_path = '~/.local/state/quickshell/user/generated/colors.json'

# [templates.hyprland]
# input_path = '~/.config/matugen/templates/hyprland/colors.conf'
# output_path = '~/.config/hypr/hyprland/colors.conf'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprland/hyprlock-colors.conf'
output_path = '~/.config/hypr/hyprlock/colors.conf'

# [templates.fuzzel]
# input_path = '~/.config/matugen/templates/fuzzel/fuzzel_theme.ini'
# output_path = '~/.config/fuzzel/fuzzel_theme.ini'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-3.0/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-4.0/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.kde_colors]
input_path = '~/.config/matugen/templates/kde/color.txt'
output_path = '~/.local/state/quickshell/user/generated/color.txt'

[templates.wallpaper]
input_path = '~/.config/matugen/templates/wallpaper.txt'
output_path = '~/.local/state/quickshell/user/generated/wallpaper/path.txt'
post_hook = 'bash ~/.config/matugen/scripts/update-wallpaper.sh "{{ image }}"'

[templates.material_scss]
input_path = '~/.config/matugen/templates/material_colors.scss'
output_path = '~/.local/state/quickshell/user/generated/material_colors.scss'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/flavors/matugen.yazi/flavor.toml'
