[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center", "--transition-fps", "60"]
set = true


[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.pywalfox]
input_path = './templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.yazi]
input_path = './templates/yazi-theme.toml'
output_path = '~/.config/yazi/flavors/matugen.yazi/flavor.toml'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/matugen.conf'
post_hook = "kitty @ set-colors -a -c ~/.config/kitty/matugen.conf"
