[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center", "--transition-fps", "60"]
set = true


[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.pywalfox]
input_path = './templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.yazi]
input_path = './templates/yazi-theme.toml'
output_path = '~/.config/yazi/flavors/matugen.yazi/flavor.toml'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/matugen.conf'

[templates.wlogout]
input_path = './templates/colors.css'
output_path = '~/.config/wlogout/matugen.css'

[templates.wlogout_lock_icon]
input_path = './templates/svg-icons/lock.svg.tmpl'
output_path = '~/.config/wlogout/icons/lock.svg'

[templates.wlogout_hibernate_icon]
input_path = './templates/svg-icons/hibernate.svg.tmpl'
output_path = '~/.config/wlogout/icons/hibernate.svg'

[templates.wlogout_logout_icon]
input_path = './templates/svg-icons/logout.svg.tmpl'
output_path = '~/.config/wlogout/icons/logout.svg'

[templates.wlogout_pause_icon]
input_path = './templates/svg-icons/pause.svg.tmpl'
output_path = '~/.config/wlogout/icons/pause.svg'

[templates.wlogout_reboot_icon]
input_path = './templates/svg-icons/reboot.svg.tmpl'
output_path = '~/.config/wlogout/icons/reboot.svg'

[templates.wlogout_shutdown_icon]
input_path = './templates/svg-icons/shutdown.svg.tmpl'
output_path = '~/.config/wlogout/icons/shutdown.svg'

[templates.swaync]
input_path = './templates/colors.scss'
output_path = '~/.config/swaync/matugen.scss'
post_hook = 'swaync-client -R'
