# https://wiki.hyprland.org/Configuring/

# exec = pgrep waybar || waybar &  # Disabled: replaced with quickshell
exec-once = qs -c ii &
# exec = pgrep albert || albert &
exec-once = vicinae server
# exec-once = swaync &  # Disabled: quickshell handles notifications now
exec-once = hypridle
exec-once = swww-daemon &
# exec-once = hyprsunset &
# exec-once = systemctl --user start hyprpolkitagent
# exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
# exec-once = wl-paste-rs --type text --watch cliphist store
# exec-once = wl-paste-rs --type image --watch cliphist store
exec-once = xrdb ~/.Xresources # Load X resources for proper DPI scaling
