# https://wiki.hyprland.org/Configuring/

###################
### MY PROGRAMS ###
###################

$qsConfig = ii
$mainMod = Super
$volumeStep = 2%

# See https://wiki.hyprland.org/Configuring/Keywords/
$terminal = kitty
$fileManager = yazi
# $menu = albert toggle
$menu = vicinae toggle
$webBrowser = zen-browser
$colorPicker = hyprpicker -a
$editor = nvim
$screenshot = grim

# Import modular configuration files from hyprland/ subdirectory
source = colors.conf
source = hyprland/colors.conf
source = hyprland/env.conf
source = hyprland/autostart.conf
source = hyprland/appearance.conf
source = hyprland/input.conf
source = hyprland/keybinds.conf
source = hyprland/window-rules.conf

###################
### XWAYLAND ###
###################

xwayland {
    force_zero_scaling = true
}

###################
### PERMISSIONS ###
###################

# See https://wiki.hyprland.org/Configuring/Permissions/

ecosystem {
    no_donation_nag = 1
#   enforce_permissions = 1
}

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow


################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor=,preferred,auto,1
# monitor = ,highres@highrr,auto,1


# monitor = desc:HAT Kamvas 13, highres@highrr, 0x0, 1, transform, 2,  mirror, DP-2
monitor = desc:HAT Kamvas 13, highres@highrr, 0x0, 1, transform, 2
monitor = desc:Dell Inc. AW3425DWM 6Q0D444, 3440x1440@180, auto, 1, bitdepth, 10, vrr, 2
monitor = desc:Ancor Communications Inc VG248 G3LMQS013154, highres@highrr, auto-right, 1



# Laptop
monitor = eDP-1,preferred,auto,1
monitor = desc: Samsung Display Corp, preferred, auto, 1.6, bitdepth, 10, cm, hdr, sdrbrightness, 1.2, sdrsaturation, 0.98, vrr, 1
# vrr | 0 = off, 1 = on, 2 = fullscreen only, 3 = fullscreen with game or video content type
