[manager]
#show_hidden = true

[opener]
play = [
    { run = 'vlc "$@"', orphan = true },
    { run = 'umpv "$@"', orphan = true },
    { run = 'mpv "$@"', orphan = true },
]
edit = [
    { run = '$EDITOR "$@"', orphan = true},
    { run = 'codium "$@"', orphan = true},
]
[open]
prepend_rules = [
	{ name = "*.html", use = [ "open", "edit" ] },
]
