# ~/.config/yazi/yazi.toml

[manager]
#show_hidden = true

[opener]
play = [
    { run = 'umpv "$@"', orphan = true },
    { run = 'mpv "$@"', orphan = true },
]
open = [
    { run = 'xdg-open "$@"', orphan = true }
]

[open]
prepend_rules = [
	{ name = "*.html", use = [ "open", "edit" ] },
]
