#!/bin/bash
# by maplepy

declare -A prefix_emoji=(
  ["init"]="🎉"

  ["fix"]="🐛"
  ["add"]="✨"
  ["feat"]="✨"
  ["perf"]="⚡️"
  ["remove"]="🔥"
  ["update"]="🔃"
  ["refactor"]="♻️"

  ["debug"]="🔍"
  ["docs"]="📚"
  ["test"]="🧪"
  ["wip"]="🚧"
  ["build"]="🏗️"
  ["deploy"]="🚀"
  ["clean"]="🧹"
  ["locale"]="🌐"
  ["release"]="🏷️"
  ["gitignore"]="🙈"
  ["chore"]="🔧"
  ["style"]="🎨"
  ["todo"]="📝"

  ["merge"]="🔀"
  ["revert"]="⏪️"
)

commit_msg_file="$1"
commit_msg_msg=$(cat "$commit_msg_file")

prefix_found=false
original_prefix=$(echo "$commit_msg_msg" | awk '{print $1}')
lowercase_prefix=$(echo "$commit_msg_msg" | awk '{print tolower($1)}')

for prefix in "${!prefix_emoji[@]}"; do
  if [[ "$lowercase_prefix" == "$prefix" ]]; then
    prefix_found=true
    break
  fi
done

if ! $prefix_found; then
  prefix="update"
fi

if [[ -z "$prefix_msg" ]]; then
  prefix_msg=$prefix
fi

commit_desc=${commit_msg_msg#"$original_prefix" }
new_commit_msg="${prefix_emoji[${prefix}]} $prefix_msg: $commit_desc"

echo -e "$new_commit_msg" >"$commit_msg_file"
