[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Beam"

[env]
TERM = "alacritty"

[font]
size = 9.0

[font.bold]
family = "JetBrainsMonoNL NFP"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL NFP"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL NFP"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL NFP"
style = "Regular"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.8
